environment:
  COVERALLS_REPO_TOKEN:
    secure: o+iKgbcKgIodN483XdvSg7VtSMx3+P/AR2ykYvOMKJ73cy4K94NPTHv8smPZA3AI
configuration: Release
platform: Any CPU
install:
  - choco install gitversion.portable -y
before_build:
  - cmd: nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo AssemblyInfoCommon.cs  /b (get-item env:APPVEYOR_REPO_BRANCH).Value
build:
  project: RgbLedSequencerLibrary.sln
  verbosity: minimal
after_build:
  - 7z a RgbLedSequencerLibrary_Release_Any_CPU.zip %APPVEYOR_BUILD_FOLDER%\src\RgbLedSequencerLibrary\bin\Release\*.dll
  - 7z a RgbLedSequencerLibrary_Release_Any_CPU.zip %APPVEYOR_BUILD_FOLDER%\src\RgbLedSequencerLibrary\bin\Release\RgbLedSequencerLibrary.pdb
  - 7z a RgbLedSequencerLibrary_Release_Any_CPU.zip %APPVEYOR_BUILD_FOLDER%\src\RgbLedSequencerLibrary\bin\Release\RgbLedSequencerLibrary.xml
  - 7z a RgbLedSequencerLibrary_Release_Any_CPU.zip %APPVEYOR_BUILD_FOLDER%\src\RgbLedSequencerLibrary\bin\Release\example-app.config
after_test:
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user "-filter:+[*]* -[*Tests]*" -target:packages\xunit.runner.console.2.2.0\tools\xunit-console.exe -targetargs:"test\unit\RgbLedSequencerLibraryTests\bin\Release\RgbLedSequencerLibraryTests.dll -noshadow" -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*Designer.cs -output:coverage.xml
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
artifacts:
  - path: RgbLedSequencerLibrary_Release_Any_CPU.zip
    name: RgbLedSequencerLibrary_Release_Any_CPU
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: 'RgbLedSequencerLibrary $(APPVEYOR_REPO_TAG_NAME)'
  description: ''
  provider: GitHub
  auth_token:
    secure: Btb4eq03u8e4+k4WUyv4mWf0kfmzuxSCRo6u1nfOCtxlr4hrdpB5af5tVpt5q+1q
  artifact: RgbLedSequencerLibrary_Release_Any_CPU
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true