-
  branches:
    only:
      - master
  environment:
    COVERALLS_REPO_TOKEN:
      secure: o+iKgbcKgIodN483XdvSg7VtSMx3+P/AR2ykYvOMKJ73cy4K94NPTHv8smPZA3AI
  configuration: Release
  platform: Any CPU
  install:
    - choco install gitversion.portable -y
  before_build:
    - nuget restore
    - gitversion /l console /output buildserver /updateassemblyinfo AssemblyInfoCommon.cs /b %APPVEYOR_REPO_BRANCH%
  build:
    project: RgbLedSequencerLibrary.sln
    verbosity: minimal
  after_build:
    - call tools\prepare-artifacts.bat
  test:
    assemblies: test\unit\RgbLedSequencerLibraryTests\bin\Release\Natsnudasoft.RgbLedSequencerLibraryTests.dll
  after_test:
    - call tools\run-test-report.bat buildserver
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  artifacts:
    - path: RgbLedSequencerLibrary_Release_Any_CPU.zip
      name: RgbLedSequencerLibrary_Release_Any_CPU
  deploy:
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: 'RgbLedSequencerLibrary $(APPVEYOR_REPO_TAG_NAME)'
    description: ''
    provider: GitHub
    auth_token:
      secure: Btb4eq03u8e4+k4WUyv4mWf0kfmzuxSCRo6u1nfOCtxlr4hrdpB5af5tVpt5q+1q
    artifact: RgbLedSequencerLibrary_Release_Any_CPU
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
-
  environment:
    COVERALLS_REPO_TOKEN:
      secure: o+iKgbcKgIodN483XdvSg7VtSMx3+P/AR2ykYvOMKJ73cy4K94NPTHv8smPZA3AI
  configuration: Release
  platform: Any CPU
  install:
    - choco install gitversion.portable -y
  before_build:
    - nuget restore
    - gitversion /l console /output buildserver /updateassemblyinfo AssemblyInfoCommon.cs /b %APPVEYOR_REPO_BRANCH%
  build:
    project: RgbLedSequencerLibrary.sln
    verbosity: minimal
  after_build:
    - call tools\prepare-artifacts.bat
  test:
    assemblies: test\unit\RgbLedSequencerLibraryTests\bin\Release\Natsnudasoft.RgbLedSequencerLibraryTests.dll
  after_test:
    - call tools\run-test-report.bat buildserver
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  artifacts:
    - path: RgbLedSequencerLibrary_Release_Any_CPU.zip
      name: RgbLedSequencerLibrary_Release_Any_CPU
