//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RgbLedSequencerLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RgbLedSequencerLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sequences command sent..
        /// </summary>
        internal static string ClearSequencesComplete {
            get {
                return ResourceManager.GetString("ClearSequencesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue command sent..
        /// </summary>
        internal static string ContinueComplete {
            get {
                return ResourceManager.GetString("ContinueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing handshake with device..
        /// </summary>
        internal static string HandshakeProgress {
            get {
                return ResourceManager.GetString("HandshakeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sequence command sent..
        /// </summary>
        internal static string PlaySequenceComplete {
            get {
                return ResourceManager.GetString("PlaySequenceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending play sequence command..
        /// </summary>
        internal static string PlaySequenceInProgress {
            get {
                return ResourceManager.GetString("PlaySequenceInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot correction read complete..
        /// </summary>
        internal static string ReadDotCorrectionComplete {
            get {
                return ResourceManager.GetString("ReadDotCorrectionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading dot correction data for LED {0}..
        /// </summary>
        internal static string ReadDotCorrectionDataProgress {
            get {
                return ResourceManager.GetString("ReadDotCorrectionDataProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence read complete..
        /// </summary>
        internal static string ReadSequenceComplete {
            get {
                return ResourceManager.GetString("ReadSequenceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading sequence data for step {0}, LED {1}..
        /// </summary>
        internal static string ReadSequenceDataProgress {
            get {
                return ResourceManager.GetString("ReadSequenceDataProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence data sent..
        /// </summary>
        internal static string SaveSequenceComplete {
            get {
                return ResourceManager.GetString("SaveSequenceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending dot correction data for LED {0}..
        /// </summary>
        internal static string SendDotCorrectionDataProgress {
            get {
                return ResourceManager.GetString("SendDotCorrectionDataProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending sequence data for step {0}, LED {1}..
        /// </summary>
        internal static string SendSequenceDataProgress {
            get {
                return ResourceManager.GetString("SendSequenceDataProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot correction data sent..
        /// </summary>
        internal static string SetDotCorrectionComplete {
            get {
                return ResourceManager.GetString("SetDotCorrectionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep command sent..
        /// </summary>
        internal static string SleepComplete {
            get {
                return ResourceManager.GetString("SleepComplete", resourceCulture);
            }
        }
    }
}
